import { api } from "./axios";
import { PageProductResponse, ProductResponse } from "@/types/product";

export interface GetProductsParams {
  page?: number;
  size?: number;
  sortBy?: string;
  direction?: string;
  companyId?: number;
}

// Omit 'id' since it's generated by the backend
export type CreateProductPayload = Omit<ProductResponse, 'id'>;

export const getProducts = (params?: GetProductsParams) => {
  return api.get<PageProductResponse>("/product", {
    params: {
      page: params?.page ?? 0,
      size: params?.size ?? 10,
      sortBy: params?.sortBy ?? "name",
      direction: params?.direction ?? "asc",
      companyId: params?.companyId ?? 0,
    }
  });
};

export const getProduct = (id: number) => {
  return api.get<ProductResponse>(`/product/${id}`);
};

export const createProduct = (payload: CreateProductPayload) => {
  return api.post<ProductResponse>("/product/add-product", payload);
};